In [ ]:
from sklearn.preprocessing import StandardScaler,OneHotEncoder,OrdinalEncoder
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.compose import ColumnTransformer
import pandas as pd

In [ ]:
df=pd.read_csv('ObesityDataSet_raw_and_data_sinthetic.csv')
df

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21,1.62,64.00,yes,no,2.0,3.0,Sometimes,no,2.00,no,0.00,1.000,no,Public_Transportation,Normal_Weight
1,Female,21,1.52,56.00,yes,no,3.0,3.0,Sometimes,yes,3.00,yes,3.00,0.000,Sometimes,Public_Transportation,Normal_Weight
2,Male,23,1.80,77.00,yes,no,2.0,3.0,Sometimes,no,2.00,no,2.00,1.000,Frequently,Public_Transportation,Normal_Weight
3,Male,27,1.80,87.00,no,no,3.0,3.0,Sometimes,no,2.00,no,2.00,0.000,Frequently,Walking,Overweight_Level_I
4,Male,22,1.78,89.80,no,no,2.0,1.0,Sometimes,no,2.00,no,0.00,0.000,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,21,1.71,131.41,yes,yes,3.0,3.0,Sometimes,no,1.73,no,1.68,0.906,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,22,1.75,133.74,yes,yes,3.0,3.0,Sometimes,no,2.01,no,1.34,0.599,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,23,1.75,133.69,yes,yes,3.0,3.0,Sometimes,no,2.05,no,1.41,0.646,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24,1.74,133.35,yes,yes,3.0,3.0,Sometimes,no,2.85,no,1.14,0.586,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,24,1.74,133.47,yes,yes,3.0,3.0,Sometimes,no,2.86,no,1.03,0.714,Sometimes,Public_Transportation,Obesity_Type_III

In [ ]:
df.isna().sum()

Gender                            0
Age                               0
Height                            0
Weight                            0
family_history_with_overweight    0
FAVC                              0
FCVC                              0
NCP                               0
CAEC                              0
SMOKE                             0
CH2O                              0
SCC                               0
FAF                               0
TUE                               0
CALC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64

In [ ]:
x=df.drop('NObeyesdad',axis=1)
y=df['NObeyesdad'].copy()

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
x_num=X_train.select_dtypes(include=np.number)
x_cat=X_train.select_dtypes(include='object')

In [ ]:
x_num_pipeline=Pipeline([
    ('scaler',StandardScaler()),
])
x_cat_pipeline=Pipeline([
    ('encoder',OneHotEncoder(sparse_output=False,handle_unknown='ignore'))
])

In [ ]:
x_num_cols=X_train.select_dtypes(include=np.number).columns
x_cat_cols=X_train.select_dtypes(include='object').columns

In [ ]:
transformer=ColumnTransformer([
    ('num',x_num_pipeline,x_num_cols),
    ('cat',x_cat_pipeline,x_cat_cols)
])
X_train_prepared=pd.DataFrame(transformer.fit_transform(X_train),columns=transformer.get_feature_names_out())
X_test_prepared=pd.DataFrame(transformer.transform(X_test),columns=transformer.get_feature_names_out())
X_test_prepared

,num__Age,num__Height,num__Weight,num__FCVC,num__NCP,num__CH2O,num__FAF,num__TUE,cat__Gender_Female,cat__Gender_Male,...,cat__SCC_yes,cat__CALC_Always,cat__CALC_Frequently,cat__CALC_Sometimes,cat__CALC_no,cat__MTRANS_Automobile,cat__MTRANS_Bike,cat__MTRANS_Motorbike,cat__MTRANS_Public_Transportation,cat__MTRANS_Walking
0,-0.686128,0.626353,-1.260870,-0.785581,1.539058,-0.239951,2.222570,2.250029,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,0.239186,-0.874253,0.935231,1.076655,0.401471,1.138507,-1.196251,-0.533369,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,-0.994566,1.591029,-1.019414,1.076655,1.679659,-0.010208,1.186202,-1.069468,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
3,-0.531909,-1.946115,-1.709289,1.076655,-2.154906,-1.651229,-1.196251,-1.069468,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4,-0.377690,0.519167,-0.482845,-0.785581,0.401471,-0.010208,-0.005025,2.250029,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
418,-0.840347,1.055098,0.015398,-0.785581,1.679659,-0.010208,1.186202,0.590281,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
419,1.010280,-0.552695,0.557333,0.909054,-0.531607,-1.651229,1.055167,-0.440423,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
420,-0.840347,1.591029,-0.827782,-0.785581,0.401471,1.630814,1.186202,0.590281,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
421,0.701842,0.626353,1.031047,-0.189666,0.401471,0.252356,-1.196251,1.362064,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
422,-0.840347,-0.016764,-0.265151,0.592474,-0.672207,-1.503537,-1.065217,-1.062829,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [ ]:
from sklearn.linear_model import LogisticRegression
full_pipe=make_pipeline(transformer, LogisticRegression(max_iter=1000))
full_pipe.fit(X_train,y_train)
full_pipe.score(X_test,y_test)

0.8723404255319149

In [ ]:
from sklearn.tree import DecisionTreeClassifier
full_pipeline=make_pipeline(transformer,DecisionTreeClassifier())
full_pipeline.fit(X_train,y_train)
full_pipeline.score(X_test,y_test)

0.9456264775413712

In [ ]:
from sklearn.ensemble import RandomForestClassifier
full_pipeline=make_pipeline(transformer,RandomForestClassifier())
full_pipeline.fit(X_train,y_train)
full_pipeline.score(X_test,y_test)

0.9479905437352246

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
full_pipeline=make_pipeline(transformer, GradientBoostingClassifier())
full_pipeline.fit(X_train,y_train)
full_pipeline.score(X_test,y_test)

0.9479905437352246